### PR TITLE
Cos expire

### LINKED ISSUE #1590: COS bucket: configuration of Archive and Expiraton policies
Ability to configure archive and expiration policies on the COS bucket with Terraform

- ibm_cos_bucket

Archive doc
https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-archive

Expiration doc
https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-expiry

Reference
https://bigblue.aha.io/features/OBJ-382
https://bigblue.aha.io/ideas/IDEA-I-3135

### LINKED ISSUE #2068: COS bucket: archive_rule overrides currently set up expiration rule
After update to a new version of ibm-cloud-terraform provider all currently set up expiration policies are deleted during terraform apply. 

Example output of terraform plan:

 ```
 Terraform will perform the following actions:

  # ibm_cos_bucket.bucket will be updated in-place
~ resource "ibm_cos_bucket" "bucket" {
        bucket_name          = "example-bucket-name"
        crn                  = "crn:v1:bluemix:public:cloud-object-storage:global:a/c7d87d30939146669d3f2bb43b2f1be7:3544f925-b0f3-4dc4-8771-a2ca0c7082b9:bucket:example-bucket-name"
        id                   = "crn:v1:bluemix:public:cloud-object-storage:global:a/c7d87d30939146669d3f2bb43b2f1be7:3544f925-b0f3-4dc4-8771-a2ca0c7082b9:bucket:example-bucket-name:meta:rl:us-east"
        region_location      = "us-east"
        resource_instance_id = "crn:v1:bluemix:public:cloud-object-storage:global:a/c7d87d30939146669d3f2bb43b2f1be7:3544f925-b0f3-4dc4-8771-a2ca0c7082b9::"
        s3_endpoint_private  = "s3.private.us-east.cloud-object-storage.appdomain.cloud"
        s3_endpoint_public   = "s3.us-east.cloud-object-storage.appdomain.cloud"
        storage_class        = "standard"

    - archive_rule {
        - days    = 0 -> null
        - enable  = true -> null
        - rule_id = "remove-data-60d-old" -> null
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
 ```

### Terraform Version
```
v0.12.29
IBM Cloud Provider version 1.15.0
```
### Affected Resource(s)
- ibm_cos_bucket

### Terraform Configuration Files
Example config:
```
resource ibm_cos_bucket bucket {
  bucket_name          = "example-bucket-name"
  resource_instance_id = "example_cos_resource_instance_id"
  region_location      = us-east
  storage_class        = "standard"
}
```
### Expected Behavior
Expiration rules should be left without changes.
### Actual Behavior
Expiration rules removed after terraform apply.
### Steps to Reproduce
1. Create a bucket in terraform
2. Set up expiration policies in console
3. Run terraform apply again

### PR DESCRIPTION
**Pull request by wderezin**
- Added support for COS expire.  expire_rule attributed added to resource_ibm_cos_bucket
- Expire rules limit each set to 1,000

closes #1590 
closed #2068

### CODE REVIEW

**Comment by wderezin** [comment]
Still need to add test cases.

File: ibm/resource_ibm_cos_bucket.go [hunk 1]
```diff
@@ -260,61 +293,114 @@ func resourceIBMCOSUpdate(d *schema.ResourceData, meta interface{}) error {
...
-				//Rule ID
-				if rule_idSet, exist := archiveMap["rule_id"]; exist {
-					id := rule_idSet.(string)
-					rule_id = id
-				}
+		var archive, archive_ok := d.GetOk("archive_rule")
+		var expire, expire_ok := d.GetOk("expire_rule")
+		var rules []*s3.LifecycleRule{}
+		if archive_ok || expire_ok {
+			if archive_ok {
```
Comment (allen-servedio) [inline ibm/resource_ibm_cos_bucket.go:302]: If possible, I would break this and the expire out into their own functions.

File: ibm/resource_ibm_cos_bucket.go [hunk 2]
```diff
@@ -260,61 +293,114 @@ func resourceIBMCOSUpdate(d *schema.ResourceData, meta interface{}) error {
...
-			archivelist := archive.([]interface{})
-			for _, l := range archivelist {
-				archiveMap, _ := l.(map[string]interface{})
-				//Rule ID
-				if rule_idSet, exist := archiveMap["rule_id"]; exist {
-					id := rule_idSet.(string)
-					rule_id = id
-				}
+		var archive, archive_ok := d.GetOk("archive_rule")
+		var expire, expire_ok := d.GetOk("expire_rule")
```
Comment (allen-servedio) [inline ibm/resource_ibm_cos_bucket.go:299]: Maybe remove `var`?

File: ibm/resource_ibm_cos_bucket.go [hunk 3]
```diff
@@ -260,61 +293,114 @@ func resourceIBMCOSUpdate(d *schema.ResourceData, meta interface{}) error {
...
+		var rules []*s3.LifecycleRule{}
```
Comment (allen-servedio) [inline ibm/resource_ibm_cos_bucket.go:300]: Don't think you need {}

**Review by allen-servedio — CHANGES_REQUESTED** [review]

File: ibm/resource_ibm_cos_bucket.go (hunk 2 above)
Comment (wderezin) [reply ibm/resource_ibm_cos_bucket.go]: It was the :=, needed to convert to =

Comment (allen-servedio) [reply ibm/resource_ibm_cos_bucket.go]: Yep that works to.

File: ibm/resource_ibm_cos_bucket_test.go [hunk 4]
```diff
@@ -508,3 +549,57 @@ func testAccCheckIBMCosBucket_update_archive(cosServiceName string, bucketName s
...
+		service           = "cloud-object-storage"
+		plan              = "lite"
+		location          = "global"
+		resource_group_id = data.ibm_resource_group.cos_group.id
+	}
+
+	resource "ibm_cos_bucket" "bucket5" {
+		bucket_name           = "%s"
+		resource_instance_id  = ibm_resource_instance.instance5.id
+	    region_location       = "%s"
```
Comment (allen-servedio) [inline ibm/resource_ibm_cos_bucket_test.go:571]: Spacing

File: ibm/resource_ibm_cos_bucket_test.go [hunk 5]
```diff
@@ -508,3 +549,57 @@ func testAccCheckIBMCosBucket_update_archive(cosServiceName string, bucketName s
...
```
Comment (allen-servedio) [inline ibm/resource_ibm_cos_bucket_test.go:601]: Spacing

File: website/docs/r/cos_bucket.html.markdown [hunk 6]
```diff
@@ -168,6 +174,13 @@ The following arguments are supported:
   *	`archive_rule.type` :* (Required, string) Specifies the storage class/archive type to which you want the object to transition. It can be Glacier or Accelerated.
 * **Note** - Archive is available in certain regions only. See Integrated Services for more details-https://cloud.ibm.com/docs/cloud-object-storage/basics?topic=cloud-object-storage-service-availability
 
+* Nested `expire_rule` block have the following structure:
+	*	`expire_rule.rule_id` : (Optional, Computed, string) Unique identifier for the rule. Expire rules allow you to set a specific time frame after which objects are deleted. 
+	*	`expire_rule.enable` :* (Required, bool) (Required) Specifies expire rule status either enable or disable for a bucket.
+
+  *	`expire_rule.days`   :* (Required, string)  Specifies the number of days when the specific rule action takes effect.
+
+  *	`expire_rule.prefix` :* (Optional, string) Specifies a prefix filter to apply to only a subset of objects with names that match the prefix.
```
Comment (allen-servedio) [inline website/docs/r/cos_bucket.html.markdown:183]: Needs to be indented to match the values above.

**Review by allen-servedio — CHANGES_REQUESTED** [review]

File: website/docs/r/cos_bucket.html.markdown [hunk 7]
```diff
@@ -158,6 +178,7 @@ The following arguments are supported:
 * `endpoint_type` - (Optional, string) The type of the endpoint (public or private) to be used for buckets. Default value is `public`.
 
 * `force_delete` - (Optional, bool) Since Default value set to True, it will delete all the objects in the COS Bucket and then delete the bucket.  Default value is `true`.
+* **Note** - force_delete will timeout on buckets with a large amount of objects.  24 hours before you delete the bucket you can set an expire rule to remove all files over a day old.
```
Comment (allen-servedio) [inline website/docs/r/cos_bucket.html.markdown:181]: I would think that you would want to indent this note so that it would appear under the `force_delete` option.

Also put `force_delete` in code backticks

File: website/docs/r/cos_bucket.html.markdown [hunk 8]
```diff
@@ -158,16 +178,24 @@ The following arguments are supported:
 * `endpoint_type` - (Optional, string) The type of the endpoint (public or private) to be used for buckets. Default value is `public`.
 
 * `force_delete` - (Optional, bool) Since Default value set to True, it will delete all the objects in the COS Bucket and then delete the bucket.  Default value is `true`.
+    * **Note** - `force_delete` will timeout on buckets with a large amount of objects.  24 hours before you delete the bucket you can set an expire rule to remove all files over a day old.  
 
 * Nested `archive_rule` block have the following structure:
 	*	`archive_rule.rule_id` : (Optional, Computed, string) Unique identifier for the rule. Archive rules allow you to set a specific time frame after which objects transition to the archive. 
 	*	`archive_rule.enable` :* (Required, bool) (Required) Specifies archive rule status either enable or disable for a bucket.
```
Comment (allen-servedio) [inline website/docs/r/cos_bucket.html.markdown:185]: Extra (Required)

File: website/docs/r/cos_bucket.html.markdown [hunk 9]
```diff
@@ -158,16 +178,24 @@ The following arguments are supported:
...
 
-  *	`archive_rule.days` :* (Required, string)  Specifies the number of days when the specific rule action takes effect.
+    *	`archive_rule.days` :* (Required, string)  Specifies the number of days when the specific rule action takes effect.
+
+    *	`archive_rule.type` :* (Required, string) Specifies the storage class/archive type to which you want the object to transition. It can be Glacier or Accelerated.
+    * **Note** - Archive is available in certain regions only. See Integrated Services for more details-https://cloud.ibm.com/docs/cloud-object-storage/basics?topic=cloud-object-storage-service-availability
+
+* Nested `expire_rule` block have the following structure:
+	*	`expire_rule.rule_id` : (Optional, Computed, string) Unique identifier for the rule. Expire rules allow you to set a specific time frame after which objects are deleted. 
+	*	`expire_rule.enable` :* (Required, bool) (Required) Specifies expire rule status either enable or disable for a bucket.
```
Comment (allen-servedio) [inline website/docs/r/cos_bucket.html.markdown:194]: Extra (Required)

File: website/docs/r/cos_bucket.html.markdown [hunk 10]
```diff
@@ -158,16 +178,24 @@ The following arguments are supported:
...
 
 * `force_delete` - (Optional, bool) Since Default value set to True, it will delete all the objects in the COS Bucket and then delete the bucket.  Default value is `true`.
+    * **Note** - `force_delete` will timeout on buckets with a large amount of objects.  24 hours before you delete the bucket you can set an expire rule to remove all files over a day old.  
 
 * Nested `archive_rule` block have the following structure:
 	*	`archive_rule.rule_id` : (Optional, Computed, string) Unique identifier for the rule. Archive rules allow you to set a specific time frame after which objects transition to the archive. 
 	*	`archive_rule.enable` :* (Required, bool) (Required) Specifies archive rule status either enable or disable for a bucket.
 
-  *	`archive_rule.days` :* (Required, string)  Specifies the number of days when the specific rule action takes effect.
+    *	`archive_rule.days` :* (Required, string)  Specifies the number of days when the specific rule action takes effect.
```
Comment (allen-servedio) [inline website/docs/r/cos_bucket.html.markdown:187]: I am not getting the `*` after the `:` on several of these fields. It is not consistent (like not all required ones it is on one optional one below)...

File: website/docs/r/cos_bucket.html.markdown [hunk 11]
```diff
@@ -128,8 +128,28 @@ resource "ibm_cos_bucket" "archive_rule_cos"{
     days = 0
     type = "GLACIER"
   }
+  expire_rule{
```
Comment (allen-servedio) [inline website/docs/r/cos_bucket.html.markdown:131]: Might be worth running the example code through `terraform fmt` as spacing is all over the place.

File: ibm/resource_ibm_cos_bucket.go [hunk 12]
```diff
@@ -225,10 +258,108 @@ func resourceIBMCOS() *schema.Resource {
 	}
 }
 
+func archiveRuleList(archiveList []interface{}) []*s3.LifecycleRule {
```
Comment (allen-servedio) [inline ibm/resource_ibm_cos_bucket.go:261]: Easier to read - thanks.

**Review by allen-servedio — CHANGES_REQUESTED** [review]

**Comment by Priyaranimishra** [comment]
Update the  resource_ibm_cos_bucket_test.go for merge of archive and expiration
Screenshot 2020-12-08 at 8 37 44 PM

Remove transition and add days and prefix  in structure.go for expiration
Screenshot 2020-12-08 at 8 39 35 PM
Update with -
if r.Expiration != nil {
      rule["days"] = int(*(r.Expiration).Days)
}
if r.Filter != nil {
      rule["prefix"] = *(r.Filter).Prefix
}

**Review by Priyaranimishra — CHANGES_REQUESTED** [review]
The terraform jenkins automation functional ID has resource_group with name "default" , Please update the test case to use Small letter (d) in default.

**Review by allen-servedio — APPROVED** [review]
Thanks for staying on top of this @wderezin and thanks for the reviews @Priyaranimishra
