### PR TITLE
fix(Cloud Databases): use V5 total math for group update request

### LINKED ISSUE #3964: The IBM database fails with Error: Unprocessable Entity
Steps 1 :

1) Create a database using `members_XXXX_XXX` (the values here for all members) argumets
```
resource "ibm_database" "database_instance" {
  name              = "test"
  service           = "databases-for-postgresql"
  plan              = "standard"
  location          = "eu-de"   
  resource_group_id = "XXXXXXXXX"
  plan_validation   = false
  
  adminpassword                = var.admin_password
  members_cpu_allocation_count = 0
  members_disk_allocation_mb = 10240
  members_memory_allocation_mb = 2048
  
 timeouts {
    create = "1440m"
    update = "120m"
    delete = "60m"
  } 

  lifecycle {
    ignore_changes = [
      # Ignore changes to tags, e.g. because a management agent
      # updates these based on some ruleset managed elsewhere.
      adminpassword,
    ]
  } 

}

```
Screenshot 2022-08-11 at 12 54 33 PM

2) Run terraform plan/apply.  After successfull provison change the tempalte to use `groups`-argument
```
resource "ibm_database" "database_instance" {
  name              = "test"
  service           = "databases-for-postgresql"
  plan              = "standard"
  location          = "eu-de"   
  resource_group_id = "XXXXXXXXX"
  plan_validation   = false
  
  adminpassword                = var.admin_password
  /*members_cpu_allocation_count = 0
  members_disk_allocation_mb = 10240
  members_memory_allocation_mb = 2048*/
  
  group {
    group_id = "member"

    memory { 
      allocation_mb = "1024" // The value here should be half of the members_memory_allocation_mb since its per member"
    }

    disk { 
      allocation_mb = "5120" // // The value here should be half of the members_disk_allocation_mb since its per member"
    }

    cpu {
      allocation_count = "0"
    }
  }
  
 timeouts {
    create = "1440m"
    update = "120m"
    delete = "60m"
  } 

  lifecycle {
    ignore_changes = [
      # Ignore changes to tags, e.g. because a management agent
      # updates these based on some ruleset managed elsewhere.
      adminpassword,
    ]
  } 

}
```
4 Now run terraform plan/apply it fails with 
```
22/08/11 14:08:51 [DEBUG] PATCH https://api.eu-de.databases.cloud.ibm.com/v5/ibm/deployments/crn:v1:bluemix:public:databases-for-postgresql:eu-de:a%!F(MISSING)1f7277194bb748cdb1d35fd8fb85a7cb:4dfe7cbe-2699-4cea-935b-f6bbe1df7766::/groups/member: timestamp=2022-08-11T14:08:51.276+0530
2022-08-11T14:08:51.895+0530 [INFO]  provider.terraform-provider-ibm_v1.42.0: 2022/08/11 14:08:51 [Debug] Response:
HTTP/2.0 422 Unprocessable Entity
Cache-Control: no-cache
Cf-Cache-Status: DYNAMIC
Cf-Ray: 738fa84b3c6da92c-MAA
Content-Security-Policy: frame-ancestors *.bluemix.net *.compose.fastkit *.cloud.ibm.com cloud.ibm.com
Content-Type: application/json; charset=utf-8
Date: Thu, 11 Aug 2022 08:38:51 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Referrer-Policy: strict-origin-when-cross-origin
Server: cloudflare
Strict-Transport-Security: max-age=0; includeSubDomains
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Envoy-Upstream-Service-Time: 431
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: e03e4d41-f319-4763-8272-f30c6d302216
X-Runtime: 0.426730
X-Xss-Protection: 1; mode=block

{"errors":{"group":["is already at that value"]}}: timestamp=2022-08-11T14:08:51.894+0530
2022-08-11T14:08:51.925+0530 [ERROR] vertex "ibm_database.database_instance" error: Unprocessable Entity
╷
│ Error: Unprocessable Entity
│ 
│   with ibm_database.database_instance,
│   on database.tf line 5, in resource "ibm_database" "database_instance":
│    5: resource "ibm_database" "database_instance" {
│ 
╵

```
It fails with this error because already members are having same values we just migrated to use groups. This scenario needs to be handle in Terraform not to throw error just update the state file with groups argument

### PR DESCRIPTION
**Pull request by alexhemard**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #3964

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccIBMDatabaseInstance'
...
--- PASS: TestAccIBMDatabaseInstanceRabbitmqImport (417.42s)
--- PASS: TestAccIBMDatabaseInstanceRedisImport (578.39s)
--- PASS: TestAccIBMDatabaseInstance_Redis_Basic (648.49s)
--- PASS: TestAccIBMDatabaseInstancePostgresImport (1056.90s)
--- PASS: TestAccIBMDatabaseInstance_Etcd_Basic (1123.47s)
--- PASS: TestAccIBMDatabaseInstance_Rabbitmq_Basic (1138.22s)
--- PASS: TestAccIBMDatabaseInstanceEtcdImport (601.54s)
--- PASS: TestAccIBMDatabaseInstanceMongodbImport (783.94s)
--- PASS: TestAccIBMDatabaseInstanceElasticsearchImport (508.76s)
--- PASS: TestAccIBMDatabaseInstanceMongodbBasic (1729.37s)
--- PASS: TestAccIBMDatabaseInstance_Elasticsearch_Basic (1096.79s)
--- PASS: TestAccIBMDatabaseInstancePostgresGroup (3181.92s)
--- PASS: TestAccIBMDatabaseInstance_Elasticsearch_Group (3558.91s)
--- PASS: TestAccIBMDatabaseInstancePostgresBasic (3556.10s)
--- PASS: TestAccIBMDatabaseInstancePostgresNode (1018.99s)
--- PASS: TestAccIBMDatabaseInstance_Elasticsearch_Node (3671.21s)
--- PASS: TestAccIBMDatabaseInstance_Cassandra_Node (8019.51s)
```

### CODE REVIEW

File: ibm/service/database/resource_ibm_database_postgresql_test.go [hunk 1]
```diff
@@ -109,6 +109,22 @@ func TestAccIBMDatabaseInstancePostgresBasic(t *testing.T) {
...
 			},
+			{
+				Config: testAccCheckIBMDatabaseInstancePostgresGroupMigration(databaseResourceGroup, testName),
+				Check: resource.ComposeAggregateTestCheckFunc(
+					testAccCheckIBMDatabaseInstanceExists(name, &databaseInstanceOne),
+					resource.TestCheckResourceAttr(name, "name", testName),
+					resource.TestCheckResourceAttr(name, "service", "databases-for-postgresql"),
+					resource.TestCheckResourceAttr(name, "plan", "standard"),
+					resource.TestCheckResourceAttr(name, "location", acc.IcdDbRegion),
+					resource.TestCheckResourceAttr(name, "groups.0.memory.0.allocation_mb", "2048"),
```
Comment (hkantare) [inline ibm/service/database/resource_ibm_database_postgresql_test.go:120]: Will this value 2048 or 1024 since its for each member right?
Did the validation did not failed here

**Comment by hkantare** [comment]
Can we return response along with err object since the err was just one line and couldn't debug wht can be the issue
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/cc329c9dcf0658bdeffb4a47407496ea7ff0cfb8/ibm/service/database/resource_ibm_database.go#L1953
and we need to see some way to set back "group" to empty list ...since its a optional even if some error occurs it stores in statefile and doesn't show diff in next run.

File: ibm/service/database/resource_ibm_database_postgresql_test.go (hunk 1 above)
Comment (alexhemard) [reply ibm/service/database/resource_ibm_database_postgresql_test.go:120]: `groups`  is a computed attribute that still populated by the V4 API / `bluemix-go` client library. It uses the total values used by the group, not per-member, so this check passes.

**Review by hkantare — APPROVED** [review]
