### PR TITLE
enhancement(sg): added filters on sg data source

### LINKED ISSUE #5386: VPC security group data source does not handle duplicate names
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

1.63.0

### Affected Resource(s)

* ibm_is_security_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "ibm_is_security_group" "smatzek_vpc_vpc_default_sg" {
  name = "vpc-default"
}
```

### Expected Behavior
I expect to have the ability to correctly use a data source to reference VPC security groups when two groups in different VPCs have the same name.

### Actual Behavior
VPC security groups are not required to have universally unique names. They are required to have the same name in a given VPC. When two security groups have the same name in different VPCs the ibm_is_security_group data source can and does lookup and get a reference to the "wrong" security group when trying to work with a specific VPC.

The arguments for the data source only allow "name". They do not allow "vpc": https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/is_security_group#argument-reference

Trying to add "vpc" as an input argument gives an error.

### Steps to Reproduce

1. create two VPC security groups with the same name in different VPCs.
2. Create some HCL with a security group data source
3. run Terraform plan
It will return one of the security groups IDs in the plan output but there is no way to choose WHICH of the conflicting named groups to use.

### References

### PR DESCRIPTION
**Pull request by ujjwal-ibm**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #5386

Output from acceptance testing:

```
$ make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISSecurityGroupDatasource_Filters'
=== RUN   TestAccIBMISSecurityGroupDatasource_Filters
--- PASS: TestAccIBMISSecurityGroupDatasource_Filters (146.92s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     149.238s
```

### CODE REVIEW

File: ibm/service/vpc/data_source_ibm_is_security_group.go [hunk 1]
```diff
@@ -46,9 +47,21 @@ func DataSourceIBMISSecurityGroup() *schema.Resource {
 
 			isSecurityGroupVPC: {
 				Type:        schema.TypeString,
+				Optional:    true,
+				Computed:    true,
+				Description: "Security group's vpc id",
+			},
+			isSgVPCName: {
+				Type:        schema.TypeString,
```
Comment (ujjwal-ibm) [inline ibm/service/vpc/data_source_ibm_is_security_group.go:55]: conflicts
