### PR TITLE
Load Balancer cannot be updated because its status is 'UPDATE_PENDING'

### LINKED ISSUE #3006: Load Balancer cannot be updated because its status is 'UPDATE_PENDING'
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
Terraform v0.15.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/ibm-cloud/ibm v1.29.0
```
### Affected Resource(s)

* ibm_is_lb

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "ibm_is_security_group" "lb_public_sg" {
  name           = "${var.resources_prefix}-lb-public-sg"
  vpc            = ibm_is_vpc.vpc.id
  resource_group = data.ibm_resource_group.group.id
}

resource "ibm_is_security_group_rule" "lb_public_sg_rule_tcp_80" {
  group     = ibm_is_security_group.lb_public_sg.id
  direction = "inbound"
  remote    = "0.0.0.0/0"
  tcp {
    port_min = 80
    port_max = 80
  }
}

resource "ibm_is_security_group_rule" "lb_public_sg_rule_tcp_outbound_80" {
  group     = ibm_is_security_group.lb_public_sg.id
  direction = "outbound"
  remote    = "0.0.0.0/0"
  tcp {
    port_min = 80
    port_max = 80
  }
}

resource "ibm_is_lb" "lb_public" {
  name            = "${var.resources_prefix}-lb-public"
  type            = "public"
  subnets         = ibm_is_subnet.sub_app.*.id
  resource_group  = data.ibm_resource_group.group.id
  security_groups = [ibm_is_security_group.lb_public_sg.id]
}
```

### Expected Behavior

The security group should be created attached to the LB and the old security group deleted from the LB as in the plan below
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # ibm_is_lb.lb_public will be updated in-place
  ~ resource "ibm_is_lb" "lb_public" {
        id                       = "r010-b6abb968-8a53-4ca9-b2ed-fea409788ce8"
        name                     = "eude-lb-public"
      ~ security_groups          = [
          - "r010-758dc16e-779f-41a2-9195-96f4ea57e81d",
        ] -> (known after apply)
        tags                     = []
        # (14 unchanged attributes hidden)
    }

  # ibm_is_security_group.lb_public_sg will be created
  + resource "ibm_is_security_group" "lb_public_sg" {
      + crn                     = (known after apply)
      + id                      = (known after apply)
      + name                    = "eude-lb-public-sg"
      + resource_controller_url = (known after apply)
      + resource_crn            = (known after apply)
      + resource_group          = "ab1c7b4a22654776801f9ae9ae436113"
      + resource_group_name     = (known after apply)
      + resource_name           = (known after apply)
      + rules                   = (known after apply)
      + tags                    = (known after apply)
      + vpc                     = "r010-211cda8c-18d5-4e37-ad49-b6fe3f90e973"
    }

  # ibm_is_security_group_rule.lb_public_sg_rule_tcp_443 will be created
  + resource "ibm_is_security_group_rule" "lb_public_sg_rule_tcp_443" {
      + direction   = "inbound"
      + group       = (known after apply)
      + id          = (known after apply)
      + ip_version  = "ipv4"
      + protocol    = (known after apply)
      + related_crn = (known after apply)
      + remote      = "0.0.0.0/0"
      + rule_id     = (known after apply)

      + tcp {
          + port_max = 443
          + port_min = 443
        }
    }

  # ibm_is_security_group_rule.lb_public_sg_rule_tcp_outbound_443 will be created
  + resource "ibm_is_security_group_rule" "lb_public_sg_rule_tcp_outbound_443" {
      + direction   = "outbound"
      + group       = (known after apply)
      + id          = (known after apply)
      + ip_version  = "ipv4"
      + protocol    = (known after apply)
      + related_crn = (known after apply)
      + remote      = "0.0.0.0/0"
      + rule_id     = (known after apply)

      + tcp {
          + port_max = 443
          + port_min = 443
        }
    }

  # ibm_is_security_group_rule.lb_public_sg_rule_tcp_outbound_80 will be created
  + resource "ibm_is_security_group_rule" "lb_public_sg_rule_tcp_outbound_80" {
      + direction   = "outbound"
      + group       = (known after apply)
      + id          = (known after apply)
      + ip_version  = "ipv4"
      + protocol    = (known after apply)
      + related_crn = (known after apply)
      + remote      = "0.0.0.0/0"
      + rule_id     = (known after apply)

      + tcp {
          + port_max = 80
          + port_min = 80
        }
    }

Plan: 4 to add, 1 to change, 0 to destroy.

```
### Actual Behavior

```
ibm_is_security_group.lb_public_sg: Creating...
ibm_is_security_group.lb_public_sg: Creation complete after 6s [id=r010-415c67db-7afd-467d-857c-1fd884ea000b]
ibm_is_security_group_rule.lb_public_sg_rule_tcp_outbound_80: Creating...
ibm_is_security_group_rule.lb_public_sg_rule_tcp_outbound_443: Creating...
ibm_is_security_group_rule.lb_public_sg_rule_tcp_443: Creating...
ibm_is_lb.lb_public: Modifying... [id=r010-b6abb968-8a53-4ca9-b2ed-fea409788ce8]
ibm_is_security_group_rule.lb_public_sg_rule_tcp_outbound_80: Creation complete after 2s [id=r010-415c67db-7afd-467d-857c-1fd884ea000b.r010-1a84929e-4e0c-4730-8636-f25ad3abab22]
ibm_is_security_group_rule.lb_public_sg_rule_tcp_outbound_443: Creation complete after 3s [id=r010-415c67db-7afd-467d-857c-1fd884ea000b.r010-7a33cce7-7809-4ec4-b391-e9d7685d8aa7]
ibm_is_security_group_rule.lb_public_sg_rule_tcp_443: Creation complete after 4s [id=r010-415c67db-7afd-467d-857c-1fd884ea000b.r010-cfd72070-c7e6-4141-b7fa-d6a57c93c02d]
╷
│ Error: Error Deleting Security Group Target for this load balancer : error communicating with LBaaS: The load balancer with ID 'r010-b6abb968-8a53-4ca9-b2ed-fea409788ce8' cannot be updated because its status is 'UPDATE_PENDING'.
│ {
│     "StatusCode": 409,
│     "Headers": {
│         "Cache-Control": [
│             "max-age=0, no-cache, no-store, must-revalidate"
│         ],
│         "Cf-Cache-Status": [
│             "DYNAMIC"
│         ],
│         "Cf-Ray": [
│             "680d28b32ecf1971-EWR"
│         ],
│         "Content-Length": [
│             "470"
│         ],
│         "Content-Type": [
│             "application/json"
│         ],
│         "Date": [
│             "Wed, 18 Aug 2021 18:20:56 GMT"
│         ],
│         "Expect-Ct": [
│             "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""
│         ],
│         "Expires": [
│             "-1"
│         ],
│         "Pragma": [
│             "no-cache"
│         ],
│         "Server": [
│             "cloudflare"
│         ],
│         "Strict-Transport-Security": [
│             "max-age=31536000; includeSubDomains"
│         ],
│         "Vary": [
│             "Accept-Encoding"
│         ],
│         "X-Content-Type-Options": [
│             "nosniff"
│         ],
│         "X-Request-Id": [
│             "3a6bc9d9-3b56-4771-9a4d-03400e04e596"
│         ],
│         "X-Xss-Protection": [
│             "1; mode=block"
│         ]
│     },
│     "Result": {
│         "errors": [
│             {
│                 "code": "load_balancer_update_conflict",
│                 "message": "error communicating with LBaaS: The load balancer with ID 'r010-b6abb968-8a53-4ca9-b2ed-fea409788ce8' cannot be updated because its status is 'UPDATE_PENDING'.",
│                 "more_info": "https://cloud.ibm.com/docs/vpc?topic=vpc-rias-error-messagesload_balancer_update_conflict",
│                 "target": {
│                     "name": "id",
│                     "type": "parameter",
│                     "value": "r010-b6abb968-8a53-4ca9-b2ed-fea409788ce8"
│                 }
│             }
│         ],
│         "trace": "3a6bc9d9-3b56-4771-9a4d-03400e04e596"
│     },
│     "RawResult": null
│ }
│ 
│ 
│   on frontend_app.tf line 101, in resource "ibm_is_lb" "lb_public":
│  101: resource "ibm_is_lb" "lb_public" {
│ 
```
### Steps to Reproduce

1. Create a VPC LB via Terraform template without a security group defined in the template (a default security group is created for it as a result)
2. Update the template to now create a security group and rules to add to the LB (the default security group will be deleted from the LB as a result)
3. Experience the failure above. 

### References

* #0000

### PR DESCRIPTION
**Pull request by SunithaGudisagarIBM**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #3006

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccIBMISLB_basic_securityGroups'

```

Tested with the below configuration:

provider "ibm" {
  ibmcloud_api_key = var.ibmcloud_api_key
  ibmcloud_timeout = 300
  region           = var.vpc_region
}

resource "ibm_is_vpc" "vpc" {
  name           = "${var.resources_prefix}-vpc"
}

resource "ibm_is_subnet" "sub_app" {
  count                    = 3
  name                     = "${var.resources_prefix}-sub-app-${count.index + 1}"
  vpc                      = ibm_is_vpc.vpc.id
  zone                     = "${var.vpc_region}-${count.index + 1}"
  total_ipv4_address_count = 16
}

resource "ibm_is_security_group" "lb_public_sg" {
  name           = "${var.resources_prefix}-lb-public-sg"
  vpc            = ibm_is_vpc.vpc.id
}

resource "ibm_is_security_group" "lb_public_sg_sun" {
  name           = "${var.resources_prefix}-lb-public-sg-sun"
  vpc            = ibm_is_vpc.vpc.id
}

resource "ibm_is_lb" "lb_public" {
  name            = "${var.resources_prefix}-lb-public"
  type            = "public"
  subnets         = ibm_is_subnet.sub_app.*.id
  // resource_group  = data.ibm_resource_group.group.id
  // security_groups = [ibm_is_security_group.lb_public_sg.id,ibm_is_security_group.lb_public_sg_sun.id]
  security_groups = ["r006-e01bbb54-9eb6-425f-9c7e-9ecd3ba5048a"]
}

Screenshot 2021-10-06 at 4 18 08 PM

Screenshot 2021-10-06 at 4 48 05 PM

### CODE REVIEW

File: ibm/resource_ibm_is_lb.go [hunk 1]
```diff
@@ -483,7 +484,9 @@ func resourceIBMISLBUpdate(d *schema.ResourceData, meta interface{}) error {
 		oSecurityGroups := o.(*schema.Set)
 		nSecurityGroups := n.(*schema.Set)
 		remove = expandStringList(oSecurityGroups.Difference(nSecurityGroups).List())
+		log.Println(remove)
 		add = expandStringList(nSecurityGroups.Difference(oSecurityGroups).List())
+		log.Println(add)
```
Comment (astha-jain) [inline ibm/resource_ibm_is_lb.go:489]: Please remove the log statements. and Could we expand on what are `o` and `n` ?

**Comment by SunithaGudisagarIBM** [comment]
@hkantare Can you please review and merge this PR, @ujjwal-ibm has already reviewed this PR, @astha-jain  @sumitkumartiwari 
Thank you very much
