### PR TITLE
Fix #1485 #1546  Update Zone for VPC cluster and worker pool

### LINKED ISSUE #1485: Race condition upgrading ibm_container_vpc_worker_pool
### Terraform Version
Terraform v0.12.24
+ provider.ibm v1.5.2

### Affected Resource(s)
ibm_container_vpc_worker_pool

### Terraform Configuration Files
```hcl
resource "ibm_container_vpc_worker_pool" "cassandra" {
  cluster           = ibm_container_vpc_cluster.cluster.id
  worker_pool_name  = "cassandra"
  flavor            = "cx2.2x4"
  vpc_id            = ibm_is_vpc.vpc.id
  worker_count      = "1"
  resource_group_id = data.ibm_resource_group.group.id
  labels = {
    dedicated = "cassandra"
  }
  zones {
    name      = "us-south-1"
    subnet_id = ibm_is_subnet.us-south-1.id
  }
  zones {
    name      = "us-south-2"
    subnet_id = ibm_is_subnet.us-south-2.id
  }
  zones {
    name      = "us-south-3"
    subnet_id = ibm_is_subnet.us-south-3.id
  }
}
```

### Expected Behavior
ibm_container_vpc_worker_pool upgraded with 2 new zones

### Actual Behavior
```
ibm_container_vpc_worker_pool.cassandra: Still destroying... [id=br37anqd0emo5cbjgkl0/br37anqd0emo5cbjgkl0-2f61d32, 15m50s elapsed]
ibm_container_vpc_worker_pool.cassandra: Still destroying... [id=br37anqd0emo5cbjgkl0/br37anqd0emo5cbjgkl0-2f61d32, 16m0s elapsed]
ibm_container_vpc_worker_pool.cassandra: Still destroying... [id=br37anqd0emo5cbjgkl0/br37anqd0emo5cbjgkl0-2f61d32, 16m10s elapsed]
ibm_container_vpc_worker_pool.cassandra: Still destroying... [id=br37anqd0emo5cbjgkl0/br37anqd0emo5cbjgkl0-2f61d32, 16m20s elapsed]
ibm_container_vpc_worker_pool.cassandra: Still destroying... [id=br37anqd0emo5cbjgkl0/br37anqd0emo5cbjgkl0-2f61d32, 16m30s elapsed]
ibm_container_vpc_worker_pool.cassandra: Destruction complete after 16m30s
ibm_container_vpc_worker_pool.cassandra: Creating...

Error: Request failed with status code: 409, ServerErrorResponse: {"incidentID":"596f44f110ea840a-KBP","code":"E0d39","description":"A worker pool with the same name already exists within the cluster. Choose another name.","type":"Provisioning"}

  on main.tf line 143, in resource "ibm_container_vpc_worker_pool" "cassandra":
 143: resource "ibm_container_vpc_worker_pool" "cassandra" {
```

### Steps to Reproduce
1. create a cluster with `ibm_container_vpc_worker_pool` having only 1 zone
2. update terraform code for `ibm_container_vpc_worker_pool` to have 3 zones

### PR DESCRIPTION
**Pull request by kavya498**

### CODE REVIEW

File: ibm/resource_ibm_container_vpc_cluster.go [hunk 1]
```diff
@@ -501,10 +499,99 @@ func resourceIBMContainerVpcClusterUpdate(d *schema.ResourceData, meta interface
 				"Error updating the worker_count %d: %s", count, err)
 		}
 	}
+	if d.HasChange("zones") {
```
Comment (hkantare) [inline ibm/resource_ibm_container_vpc_cluster.go:502]: add && !d.IsNewResource() also

File: ibm/resource_ibm_container_vpc_cluster.go [hunk 2]
```diff
@@ -501,10 +499,99 @@ func resourceIBMContainerVpcClusterUpdate(d *schema.ResourceData, meta interface
...
+					zoneParam := v2.WorkerPoolZone{
+						Cluster:      clusterID,
+						Id:           newPack["name"].(string),
+						SubnetID:     newPack["subnet_id"].(string),
+						WorkerPoolID: "default",
+					}
+					err = csClient.WorkerPools().CreateWorkerPoolZone(zoneParam, targetEnv)
+					if err != nil {
+						return fmt.Errorf("Error adding zone to conatiner vpc cluster: %s", err)
+					}
```
Comment (hkantare) [inline ibm/resource_ibm_container_vpc_cluster.go:526]: Add wait logic to even wait for zone and workers to be ready..Use existing WaitForWorkerPoolAvailable
