### PR TITLE
CBR typeset change for cbr rule/zone and adding CBR retries

### LINKED ISSUE #4171: Provider incorrectly seems to detect a change, applies it - next apply incorrectly detects the same change
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version
```
$ terraform -v
Terraform v1.3.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/kubernetes v2.11.0
+ provider registry.terraform.io/hashicorp/null v3.2.0
+ provider registry.terraform.io/ibm-cloud/ibm v1.47.1

```
### Affected Resource(s)

* ibm_cbr_rule

### Terraform Configuration Files

This is the resource which I could apply n times, like in an infinite loop.

```hcl
# registry access
resource "ibm_cbr_rule" "cbr_rule_registry" {
  contexts {
    attributes {
      name  = "networkZoneId"
      value = ibm_cbr_zone.cbr_zone_k8s.id
    }
  }

  description      = "restrict access to registry to cluster"
  enforcement_mode = var.cbr_enforcement_mode
  resources {
    attributes {
      name  = "accountId"
      value = data.ibm_iam_account_settings.team_iam_account_settings.account_id
    }
    attributes {
      name     = "resourceType"
      operator = "stringEquals"
      value    = "namespace"
    }
    attributes {
      name     = "resource"
      operator = "stringEquals"
      value    = "henrik/bluegreen"
    }
    attributes {
      name     = "serviceName"
      operator = "stringEquals"
      value    = "container-registry"
    }

  }
}

```

### Debug Output```

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # ibm_cbr_rule.cbr_rule_registry will be updated in-place
  ~ resource "ibm_cbr_rule" "cbr_rule_registry" {
        id                  = "31e9546169c70af51a0899ad8d7d4e8d"
        # (9 unchanged attributes hidden)

      ~ resources {
          ~ attributes {
              ~ name     = "resource" -> "resourceType"
              ~ value    = "henrik/bluegreen" -> "namespace"
                # (1 unchanged attribute hidden)
            }
          ~ attributes {
              ~ name     = "resourceType" -> "resource"
              ~ value    = "namespace" -> "henrik/bluegreen"
                # (1 unchanged attribute hidden)
            }

            # (2 unchanged blocks hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes 

ibm_cbr_rule.cbr_rule_registry: Modifying... [id=31e9546169c70af51a0899ad8d7d4e8d]
ibm_cbr_rule.cbr_rule_registry: Modifications complete after 1s [id=31e9546169c70af51a0899ad8d7d4e8d]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
<!---
Please provide a link to a GitHub Gist containing the complete debug output. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

To obtain the debug output, see the [Terraform documentation on debugging](https://www.terraform.io/docs/internals/debugging.html).
--->

### Panic Output

<!--- If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`. --->

### Expected Behavior
I expect the resource, when applied once, to be stable. When I call "apply" again there should be not changes.
<!--- What should have happened? --->

### Actual Behavior
Whenever I apply again, a change is detected and the resource updated. The ID remains the same. On the next apply, the same resource is updated again.
<!--- What actually happened? --->

### Steps to Reproduce

<!--- Please list the steps required to reproduce the issue. --->

1. `terraform apply`

### Important Factoids

<!--- Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? --->

### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor documentation? For example:
--->

* #0000

### LINKED ISSUE #4971: [CBR rule] IAM GET API failure causing issue with CBR rule creation
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ibm_cbr_zone
* ibm_cbr_rule

### Terraform Configuration Files

[CBR](https://github.com/terraform-ibm-modules/terraform-ibm-cbr/blob/main/modules/cbr-rule-module/main.tf#L7C11-L7C23) created for example for a [Event Notification](https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/blob/main/examples/complete/main.tf)

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Debug Output

```
TestRunCompleteExample 2023-11-28T06:13:43Z logger.go:66: module.event_notification.module.cbr_rule[0].ibm_cbr_rule.cbr_rule: Creating...
TestRunCompleteExample 2023-11-28T06:13:43Z logger.go:66: module.event_notification.ibm_resource_key.service_credentials["en_status_reporter"]: Creation complete after 7s [id=crn:v1:bluemix:public:event-notifications:us-south:a/abac0df06b644a9cabc6e44f55b3880e:71d50167-d0c3-4b7b-93e0-26813d026064:resource-key:67e4e87c-8dc1-40c7-98d4-5fbde22b25be]
TestRunCompleteExample 2023-11-28T06:13:44Z logger.go:66: module.event_notification.ibm_en_integration.en_kms_integration[0]: Creation complete after 2s [id=71d50167-d0c3-4b7b-93e0-26813d026064/13b5942b-b29e-4bee-a113-b76a786bf68d]
TestRunCompleteExample 2023-11-28T06:13:45Z logger.go:66: module.event_notification.ibm_resource_key.service_credentials["en_event_notifications_publisher"]: Creation complete after 8s [id=crn:v1:bluemix:public:event-notifications:us-south:a/abac0df06b644a9cabc6e44f55b3880e:71d50167-d0c3-4b7b-93e0-26813d026064:resource-key:9213adf1-10da-4a3d-8755-ba67080b7a68]
TestRunCompleteExample 2023-11-28T06:13:45Z logger.go:66: module.event_notification.ibm_resource_key.service_credentials["en_writer"]: Creation complete after 5s [id=crn:v1:bluemix:public:event-notifications:us-south:a/abac0df06b644a9cabc6e44f55b3880e:71d50167-d0c3-4b7b-93e0-26813d026064:resource-key:cb3c22cd-a650-4322-9116-2ef7ca039e83]
TestRunCompleteExample 2023-11-28T06:13:45Z logger.go:66: module.event_notification.ibm_resource_key.service_credentials["en_manager"]: Creation complete after 9s [id=crn:v1:bluemix:public:event-notifications:us-south:a/abac0df06b644a9cabc6e44f55b3880e:71d50167-d0c3-4b7b-93e0-26813d026064:resource-key:d9fa9bf8-f387-4be5-941a-8fde3d704222]
TestRunCompleteExample 2023-11-28T06:13:46Z logger.go:66: module.event_notification.ibm_resource_key.service_credentials["en_event_source_manager"]: Still creating... [10s elapsed]
TestRunCompleteExample 2023-11-28T06:13:46Z logger.go:66: module.event_notification.ibm_resource_key.service_credentials["en_custom_email_status_reporter"]: Still creating... [10s elapsed]
TestRunCompleteExample 2023-11-28T06:13:48Z logger.go:66: module.event_notification.ibm_resource_key.service_credentials["en_custom_email_status_reporter"]: Creation complete after 12s [id=crn:v1:bluemix:public:event-notifications:us-south:a/abac0df06b644a9cabc6e44f55b3880e:71d50167-d0c3-4b7b-93e0-26813d026064:resource-key:ec6ed11d-6f9e-4bc8-ac4b-f0d4edba51b5]
TestRunCompleteExample 2023-11-28T06:13:50Z logger.go:66: module.event_notification.ibm_resource_key.service_credentials["en_event_source_manager"]: Creation complete after 13s [id=crn:v1:bluemix:public:event-notifications:us-south:a/abac0df06b644a9cabc6e44f55b3880e:71d50167-d0c3-4b7b-93e0-26813d026064:resource-key:55bbeaff-ba06-4ea9-b97c-2a56f75f69b1]
TestRunCompleteExample 2023-11-28T06:13:51Z logger.go:66: module.event_notification.time_sleep.wait_for_authorization_policy: Still creating... [10s elapsed]
TestRunCompleteExample 2023-11-28T06:13:51Z logger.go:66: ibm_is_subnet.testacc_subnet: Still creating... [10s elapsed]
TestRunCompleteExample 2023-11-28T06:13:55Z logger.go:66: ibm_is_subnet.testacc_subnet: Creation complete after 14s [id=0717-06736443-3975-4ef2-8c5a-8c7062336eb2]
TestRunCompleteExample 2023-11-28T06:14:01Z logger.go:66: module.event_notification.time_sleep.wait_for_authorization_policy: Still creating... [20s elapsed]
TestRunCompleteExample 2023-11-28T06:14:11Z logger.go:66: module.event_notification.time_sleep.wait_for_authorization_policy: Still creating... [30s elapsed]
TestRunCompleteExample 2023-11-28T06:14:11Z logger.go:66: module.event_notification.time_sleep.wait_for_authorization_policy: Creation complete after 30s [id=2023-11-28T06:14:11Z]
TestRunCompleteExample 2023-11-28T06:14:11Z logger.go:66: ╷
TestRunCompleteExample 2023-11-28T06:14:11Z logger.go:66: │ Error: CreateRuleWithContext failed The network zone '9cc6953333f87740301f98a1017dd929' is not found.
TestRunCompleteExample 2023-11-28T06:14:11Z logger.go:66: │ {
TestRunCompleteExample 2023-11-28T06:14:11Z logger.go:66: │     "StatusCode": 404,
TestRunCompleteExample 2023-11-28T06:14:11Z logger.go:66: │     "Headers": {
TestRunCompleteExample 2023-11-28T06:14:11Z logger.go:66: │         "Akamai-Grn": [
TestRunCompleteExample 2023-11-28T06:14:11Z logger.go:66: │             "0.88f8cd17.1701152023.35d34cab"
```
Above TF apply log indicates that the CBR zone (zone id: 9cc6953333f87740301f98a1017dd929) was created but when the CBR rule was being created using this zone id it failed with  `zone is not found`.

### Trace Log

Attached [Trace log](https://github.com/IBM-Cloud/terraform-provider-ibm/files/13590726/trace.log) shows failure of this GET API- GET https://iam.cloud.ibm.com/v2/roles?account_id=abac0df06b644a9cabc6e44f55b3880e&service_name=event-notifications, resulting in `resource not found` even though the zone was created, leading to the failure of the test example.

```
 : timestamp=2023-11-28T06:13:43.267Z
2023-11-28T06:13:43.267Z [INFO]  provider.terraform-provider-ibm_v1.59.1: 2023/11/28 06:13:43 [DEBUG] GET https://iam.cloud.ibm.com/v2/roles?account_id=abac0df06b644a9cabc6e44f55b3880e&service_name=event-notifications: timestamp=2023-11-28T06:13:43.267Z
2023-11-28T06:13:43.371Z [INFO]  provider.terraform-provider-ibm_v1.59.1: 2023/11/28 06:13:43 [Debug] Response:
HTTP/1.1 404 Not Found 
```

### Expected Behavior

The CBR rule should be created.

### Actual Behavior

CBR rule fails to create.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### LINKED ISSUE #5002: [CBR] Provider produced inconsistent result after apply
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Terraform Version v1.5.7
Terraform IBM Provider Version v1.60.1

### Affected Resource(s)

* ibm_cbr_zone

### Terraform Configuration Files

We have noticed an issue during one of the test for [TF Event Notification module example](https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/tree/main/examples/complete) which is 

```
Provider produced inconsistent result after apply

When applying changes to module.cbr_zone.ibm_cbr_zone.cbr_zone, provider
"provider[\"registry.terraform.io/ibm-cloud/ibm\"]" produced an unexpected
new value: Root resource was present, but now absent.
This is a bug in the provider, which should be reported in the provider's
own issue tracker.
```

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Debug Output

Adding Logs
[TF_debug.log](https://github.com/IBM-Cloud/terraform-provider-ibm/files/13715768/trace.log)
[TF_stdout.txt](https://github.com/IBM-Cloud/terraform-provider-ibm/files/13715774/stdout.txt)

### Expected Behavior

All the zones should get created/destroyed during the TF operation.

### Actual Behavior

Provider produced inconsistent result after apply.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by tyao117**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000
Closes #4171
Closes #5002 
Closes #4971

Output from acceptance testing:

```shell
$ make testacc TESTARGS='-run=TEST=./ibm/service/contextbasedrestrictions'
=== RUN   TestAccIBMCbrRuleDataSourceBasic
--- PASS: TestAccIBMCbrRuleDataSourceBasic (12.91s)
=== RUN   TestAccIBMCbrRuleDataSourceAllArgs
--- PASS: TestAccIBMCbrRuleDataSourceAllArgs (11.39s)
=== RUN   TestAccIBMCbrZoneDataSourceBasic
--- PASS: TestAccIBMCbrZoneDataSourceBasic (10.23s)
=== RUN   TestAccIBMCbrZoneDataSourceAllArgs
--- PASS: TestAccIBMCbrZoneDataSourceAllArgs (9.41s)
=== RUN   TestAccIBMCbrRuleBasic
--- PASS: TestAccIBMCbrRuleBasic (10.01s)
=== RUN   TestAccIBMCbrRuleAllArgs
--- PASS: TestAccIBMCbrRuleAllArgs (18.06s)
=== RUN   TestAccIBMCbrZoneBasic
--- PASS: TestAccIBMCbrZoneBasic (9.40s)
=== RUN   TestAccIBMCbrZoneAllArgs
--- PASS: TestAccIBMCbrZoneAllArgs (18.45s)
PASS

...
```

### CODE REVIEW

**Comment by tyao117** [comment]
showing the change of the retry:
```shell
...
{"trace":"3a1c7778-0c97-44e3-a46d-1ab29f7c6740","errors":[{"code":"rule_not_found_in_store","message":"The rule 'd38463f844a13ed98eb97c48f909cb5a' is not found in store.","target":{"type":"parameter","name":"rule_id","value":"d38463f844a13ed98eb97c48f909cb5a"}}],"status_code":404}: timestamp=2024-03-28T17:19:52.226-0500
2024-03-28T17:19:52.228-0500 [INFO]  provider.terraform-provider-ibm: Read cbr rule response status code: 404, provider will try again. The rule 'd38463f844a13ed98eb97c48f909cb5a' is not found in store.: timestamp=2024-03-28T17:19:52.228-0500
ibm_cbr_rule.cbr_rule: Still creating... [10s elapsed]
ibm_cbr_rule.cbr_rule: Still creating... [20s elapsed]
2024-03-28T17:20:12.231-0500 [INFO]  provider.terraform-provider-ibm: 2024/03/28 17:20:12 [Debug] Request:
GET /v1/rules/d38463f844a13ed98eb97c48f909cb5a HTTP/1.1
Host: testing-1-ap-south.network-policy.cloud.ibm.com
User-Agent: platform-services-go-sdk/0.61.2 (lang=go; arch=arm64; os=darwin; go.version=go1.21.6)
Accept: application/json
Authorization: [redacted]
X-Original-User-Agent: terraform-provider-ibm/1.64.0-beta0
Accept-Encoding: gzip
: timestamp=2024-03-28T17:20:12.231-0500
2024-03-28T17:20:12.231-0500 [INFO]  provider.terraform-provider-ibm: 2024/03/28 17:20:12 [DEBUG] GET https://testing-1-ap-south.network-policy.cloud.ibm.com/v1/rules/d38463f844a13ed98eb97c48f909cb5a: timestamp=2024-03-28T17:20:12.231-0500
2024-03-28T17:20:12.810-0500 [INFO]  provider.terraform-provider-ibm: 2024/03/28 17:20:12 [Debug] Response:
HTTP/2.0 200 OK
Content-Length: 973
Akamai-Grn: 0.b8764017.1711664412.1a11d10
Cache-Control: max-age=0, no-cache, no-store
Content-Type: application/json; charset=utf-8
Date: Thu, 28 Mar 2024 22:20:12 GMT
Etag: 1-e7fe6ccc1aa9b260cf9a75f5545918a6
Expires: Thu, 28 Mar 2024 22:20:12 GMT
Pragma: no-cache
Set-Cookie: ak_bmsc=37096D28113F036166B2AA3D9403EEE0~000000000000000000000000000000~YAAQuHZAFxv5bIWOAQAAWTgmhxePEw5ueSfjnxhMfnqRSHvgfHLXQektil3fPL3Z0SUvHu2h6pLB3B7YDwaLWizjHNS/f1G5g9SFMt4CWlxyu8IdhW+Jt4gUpZw8JJnPpiuarrtOa9v1KbHRW3lw8eAWbvZIgIOcfRCpiK1/sp1S0MiQkKINLh6hy47fecDPglJ5fivjKV0qTear550LZBdJxwJyx26o8grj2jW0ldNNa+Zz5c4XWs4F5970JSGTNXjKVF1NLpneYyNIA1JX/JAWnMdAzeZIi33Gu3LB5GDxquX4rEGvMDcqL5ZK50It9YcEeLJbrFPD68YEf6sgqIhqvjeemNAdWD0ySPt4wSodL60hdDI2IqSLWacKPO854YPdM3icg6bgi8d1XXGwZWtTj5ycQ/nq6K8=; Domain=.network-policy.cloud.ibm.com; Path=/; Expires=Fri, 29 Mar 2024 00:20:12 GMT; Max-Age=7200; HttpOnly
Strict-Transport-Security: max-age=31536000; includeSubDomains
Transaction-Id: 4ed26f8b-658b-4676-8c30-aabca0a75ef8
X-Content-Type-Options: nosniff
X-Correlation-Id: 4ed26f8b-658b-4676-8c30-aabca0a75ef8
X-Proxy-Upstream-Service-Time: 91
X-Ratelimit-Limit: 10
X-Ratelimit-Remaining: 9
X-Ratelimit-Reset: 1711664413

{"description":"test rule config basic","resources":[{"attributes":[{"name":"accountId","value":"37cb83958369439db2ef3d6156f82b9d"},{"name":"serviceName","value":"user-management"}],"tags":[{"name":"tag_name","value":"tag_value"}]}],"contexts":[{"attributes":[{"name":"networkZoneId","value":"3cbe2e308ead56b8021b8a8618089776"}]}],"operations":{"api_types":[{"api_type_id":"crn:v1:bluemix:public:context-based-restrictions::::api-type:","display_name":"All","description":"Protects all service APIs."}]},"enforcement_mode":"disabled","id":"d38463f844a13ed98eb97c48f909cb5a","crn":"crn:v1:bluemix:public:context-based-restrictions:global:a/37cb83958369439db2ef3d6156f82b9d::rule:d38463f844a13ed98eb97c48f909cb5a","href":"https://testing-1-ap-south.network-policy.cloud.ibm.com/v1/rules/d38463f844a13ed98eb97c48f909cb5a","created_at":"2024-03-28T22:19:51Z","created_by_id":"IBMid-550003PATQ","last_modified_at":"2024-03-28T22:19:51Z","last_modified_by_id":"IBMid-550003PATQ"}: timestamp=2024-03-28T17:20:12.810-0500
2024-03-28T17:20:12.811-0500 [INFO]  provider.terraform-provider-ibm: 2024/03/28 17:20:12 [Debug] Request:
GET /v1/rules/d38463f844a13ed98eb97c48f909cb5a HTTP/1.1
Host: testing-1-ap-south.network-policy.cloud.ibm.com
User-Agent: platform-services-go-sdk/0.61.2 (lang=go; arch=arm64; os=darwin; go.version=go1.21.6)
Accept: application/json
Authorization: [redacted]
X-Original-User-Agent: terraform-provider-ibm/1.64.0-beta0
Accept-Encoding: gzip
: timestamp=2024-03-28T17:20:12.811-0500
2024-03-28T17:20:12.811-0500 [INFO]  provider.terraform-provider-ibm: 2024/03/28 17:20:12 [DEBUG] GET https://testing-1-ap-south.network-policy.cloud.ibm.com/v1/rules/d38463f844a13ed98eb97c48f909cb5a: timestamp=2024-03-28T17:20:12.811-0500
2024-03-28T17:20:13.333-0500 [INFO]  provider.terraform-provider-ibm: 2024/03/28 17:20:13 [Debug] Response:
HTTP/2.0 200 OK
Content-Length: 973
Akamai-Grn: 0.b8764017.1711664412.1a12088
Cache-Control: max-age=0, no-cache, no-store
Content-Type: application/json; charset=utf-8
Date: Thu, 28 Mar 2024 22:20:13 GMT
Etag: 1-e7fe6ccc1aa9b260cf9a75f5545918a6
Expires: Thu, 28 Mar 2024 22:20:13 GMT
Pragma: no-cache
Set-Cookie: ak_bmsc=57DD90F650B835369E48F77FAEB2209C~000000000000000000000000000000~YAAQuHZAF1D5bIWOAQAAOjomhxest+gYrOohHxPLLJ83wAD9MzG8dUVxhgdKHMc3nlUQUU8NEYV9NDYf1/GotFqwYBMCldU3hN36WPunj/nkexg3SAiBV9hW9LCedE6shpGNOGvHuIQaAylZebiHhDKzGVfT73oyPasa/latgu49ImB9I3dYwrFfmmaAHNJB+ABx7g/JNjZ3V0tkunACjGG3tXgzBGwTi0MX/jREZdrmgZpqTW3OLo3iZr3eZcnxyI9c4kxO13Xv+h3Mm6kTfHcC5/BzXYyV0UMzP/fWq4+jfn0Z+X9JjSSAJGvWLr4Cr6Jkb6MdifKUH+PdX4uM7RQPf1mzhuGqpuDYmz0rbRwOT0nNRFFhdWZp1XuDLp0VeXSQyE3xnP+/AvxdM1yxppEPNhF4RGUWKww=; Domain=.network-policy.cloud.ibm.com; Path=/; Expires=Fri, 29 Mar 2024 00:20:12 GMT; Max-Age=7199; HttpOnly
Strict-Transport-Security: max-age=31536000; includeSubDomains
Transaction-Id: 9bbf37ef-3261-4dc2-90ed-991ccb535306
X-Content-Type-Options: nosniff
X-Correlation-Id: 9bbf37ef-3261-4dc2-90ed-991ccb535306
X-Proxy-Upstream-Service-Time: 54
X-Ratelimit-Limit: 10
X-Ratelimit-Remaining: 8
X-Ratelimit-Reset: 1711664413

{"description":"test rule config basic","resources":[{"attributes":[{"name":"accountId","value":"37cb83958369439db2ef3d6156f82b9d"},{"name":"serviceName","value":"user-management"}],"tags":[{"name":"tag_name","value":"tag_value"}]}],"contexts":[{"attributes":[{"name":"networkZoneId","value":"3cbe2e308ead56b8021b8a8618089776"}]}],"operations":{"api_types":[{"api_type_id":"crn:v1:bluemix:public:context-based-restrictions::::api-type:","display_name":"All","description":"Protects all service APIs."}]},"enforcement_mode":"disabled","id":"d38463f844a13ed98eb97c48f909cb5a","crn":"crn:v1:bluemix:public:context-based-restrictions:global:a/37cb83958369439db2ef3d6156f82b9d::rule:d38463f844a13ed98eb97c48f909cb5a","href":"https://testing-1-ap-south.network-policy.cloud.ibm.com/v1/rules/d38463f844a13ed98eb97c48f909cb5a","created_at":"2024-03-28T22:19:51Z","created_by_id":"IBMid-550003PATQ","last_modified_at":"2024-03-28T22:19:51Z","last_modified_by_id":"IBMid-550003PATQ"}: timestamp=2024-03-28T17:20:13.332-0500
2024-03-28T17:20:13.335-0500 [WARN]  Provider "provider[\"github.ibm.com/ibm-cloud/ibm\"]" produced an unexpected new value for ibm_cbr_rule.cbr_rule, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .transaction_id: was null, but now cty.StringVal("")
      - .x_correlation_id: was null, but now cty.StringVal("")
      - .resources[0].tags[0].operator: was null, but now cty.StringVal("")
ibm_cbr_rule.cbr_rule: Creation complete after 22s [id=d38463f844a13ed98eb97c48f909cb5a]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

**Comment by ocofaigh** [comment]
@zhenwan you might want to review?

File: ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go [hunk 1]
```diff
@@ -305,24 +318,58 @@ func resourceIBMCbrRuleCreate(context context.Context, d *schema.ResourceData, m
...
 
 	getRuleOptions := &contextbasedrestrictionsv1.GetRuleOptions{}
-
 	getRuleOptions.SetRuleID(d.Id())
 
 	rule, response, err := contextBasedRestrictionsClient.GetRuleWithContext(context, getRuleOptions)
 	if err != nil {
+		//  Manual change. leverage retry for the read due to eventual consistency of the service.
 		if response != nil && response.StatusCode == 404 {
-			d.SetId("")
```
Comment (hkantare) [inline ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go:321]: Chane the retry logic to use Resource.RetryContext 
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/b8c55bb204c494ff3bf049521e75c92c473f5dd4/ibm/service/iamaccessgroup/resource_ibm_iam_access_group.go#L90

File: ibm/service/contextbasedrestrictions/resource_ibm_cbr_zone.go [hunk 2]
```diff
@@ -291,24 +305,58 @@ func resourceIBMCbrZoneCreate(context context.Context, d *schema.ResourceData, m
...
 	getZoneOptions := &contextbasedrestrictionsv1.GetZoneOptions{}
-
 	getZoneOptions.SetZoneID(d.Id())
 
 	zone, response, err := contextBasedRestrictionsClient.GetZoneWithContext(context, getZoneOptions)
 	if err != nil {
 		if response != nil && response.StatusCode == 404 {
-			d.SetId("")
-			return nil
+			//  Manual change. leverage retry for the read due to eventual consistency of the service.
```
Comment (hkantare) [inline ibm/service/contextbasedrestrictions/resource_ibm_cbr_zone.go:345]: similar comment

**Comment by zhenwan** [comment]
@ocofaigh yes

File: ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go (hunk 1 above)
Comment (tyao117) [reply ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go:321]: Resource.RetryContext is considered deprecated.
https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource#RetryableError

File: ibm/service/contextbasedrestrictions/resource_ibm_cbr_zone.go (hunk 2 above)
Comment (hkantare) [reply ibm/service/contextbasedrestrictions/resource_ibm_cbr_zone.go:345]: We can use retry.RetryContext instead of Resource.RetryContext  as sugested in deprecation

File: ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go [hunk 3]
```diff
@@ -68,7 +82,7 @@ func ResourceIBMCbrRule() *schema.Resource {
 				Elem: &schema.Resource{
 					Schema: map[string]*schema.Schema{
 						"attributes": &schema.Schema{
-							Type:        schema.TypeList,
+							Type:        schema.TypeSet,
```
Comment (zhenwan) [inline ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go:85]: Should other types,  `contexts`, `tags`, `api_types`, change to `schema.TypeSet`  too? Those should be unordered collection of items

File: ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go [hunk 4]
```diff
@@ -305,24 +318,58 @@ func resourceIBMCbrRuleCreate(context context.Context, d *schema.ResourceData, m
...
+func waitForCbrRuleRead(cbrClient *contextbasedrestrictionsv1.ContextBasedRestrictionsV1, context context.Context, id string, timeout time.Duration) (interface{}, error) {
+	stateConf := &retry.StateChangeConf{
+		Pending: []string{cbrRuleReadPending},
+		Target:  []string{cbrRuleReadError, cbrRuleReadComplete, ""},
+		Refresh: func() (interface{}, string, error) {
+			log.Printf("[DEBUG] Read cbr rule (%s) read", id)
+			getRuleOptions := &contextbasedrestrictionsv1.GetRuleOptions{}
+			getRuleOptions.SetRuleID(id)
+			_, response, err := cbrClient.GetRuleWithContext(context, getRuleOptions)
+			if err != nil && response.StatusCode == 404 {
```
Comment (zhenwan) [inline ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go:331]: better to have log output here and waiting time for next try

File: ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go [hunk 5]
```diff
@@ -305,24 +318,58 @@ func resourceIBMCbrRuleCreate(context context.Context, d *schema.ResourceData, m
...
-
 	getRuleOptions.SetRuleID(d.Id())
 
 	rule, response, err := contextBasedRestrictionsClient.GetRuleWithContext(context, getRuleOptions)
 	if err != nil {
+		//  Manual change. leverage retry for the read due to eventual consistency of the service.
 		if response != nil && response.StatusCode == 404 {
-			d.SetId("")
-			return nil
+			log.Printf("[INFO] Read cbr rule response status code: 404, provider will try again. %s", err)
```
Comment (zhenwan) [inline ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go:359]: add sleeping time before call  `waitForCbrRuleRead` ?

File: ibm/service/contextbasedrestrictions/resource_ibm_cbr_zone.go [hunk 6]
```diff
@@ -291,24 +305,58 @@ func resourceIBMCbrZoneCreate(context context.Context, d *schema.ResourceData, m
...
+func waitForCbrZoneRead(cbrClient *contextbasedrestrictionsv1.ContextBasedRestrictionsV1, context context.Context, id string, timeout time.Duration) (interface{}, error) {
+	stateConf := &retry.StateChangeConf{
+		Pending: []string{cbrRuleReadPending},
+		Target:  []string{cbrRuleReadError, cbrRuleReadComplete, ""},
+		Refresh: func() (interface{}, string, error) {
+			log.Printf("[INFO] Retrying cbr rule (%s) read", id)
+			getZoneOptions := &contextbasedrestrictionsv1.GetZoneOptions{}
+			getZoneOptions.SetZoneID(id)
+			_, response, err := cbrClient.GetZoneWithContext(context, getZoneOptions)
+			if err != nil && response.StatusCode == 404 {
```
Comment (zhenwan) [inline ibm/service/contextbasedrestrictions/resource_ibm_cbr_zone.go:318]: better to have log output with error and waiting time for next try if the `retry` does not do it

File: ibm/service/contextbasedrestrictions/resource_ibm_cbr_zone.go [hunk 7]
```diff
@@ -291,24 +305,58 @@ func resourceIBMCbrZoneCreate(context context.Context, d *schema.ResourceData, m
...
-
 	getZoneOptions.SetZoneID(d.Id())
 
 	zone, response, err := contextBasedRestrictionsClient.GetZoneWithContext(context, getZoneOptions)
 	if err != nil {
 		if response != nil && response.StatusCode == 404 {
-			d.SetId("")
-			return nil
+			//  Manual change. leverage retry for the read due to eventual consistency of the service.
+			log.Printf("[INFO] Read cbr zone response status code: 404, provider will try again. %s", err)
```
Comment (zhenwan) [inline ibm/service/contextbasedrestrictions/resource_ibm_cbr_zone.go:346]: add sleeping time before call  `waitForCbrZoneRead` ?

File: ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go [hunk 8]
```diff
@@ -305,24 +318,58 @@ func resourceIBMCbrRuleCreate(context context.Context, d *schema.ResourceData, m
...
+				d.SetId("")
+				return diag.FromErr(fmt.Errorf("GetRuleWithContext failed %s\n%s", err, response))
+			}
+			// Read the rule again because there are no errors
+			rule, _, _ = contextBasedRestrictionsClient.GetRuleWithContext(context, getRuleOptions)
+			// end Manual Change
+		} else {
+			log.Printf("[DEBUG] GetRuleWithContext failed %s\n%s", err, response)
+			return diag.FromErr(fmt.Errorf("GetRuleWithContext failed %s\n%s", err, response))
 		}
```
Comment (hkantare) [inline ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go:372]: This logic handle the case when CBR rule is deleted outside Terraform context and when user runs plan it should diff a new resource will be created instead of throwing error 
Move this wait logic here after creation wait till its acauires desired state https://github.com/IBM-Cloud/terraform-provider-ibm/blob/6ad4c774b6dbb4c02dc31958a3664d34d38d8826/ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go#L317

Comment (zhenwan) [reply ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go:372]: @hkantare I don't agree with your comment above.  The code you highlighted above is already in [the master branch ](https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go#L324-L325) which is utilized to manage rule read errors if the StatusCode is not 404

The logic Tim updated to the function `resourceIBMCbrRuleRead` is to handle the [Eventual consistency issue ](https://cloud.ibm.com/docs/account?topic=account-known-issues#cbr-eventual-consistency) that a user reported [here](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5002#issuecomment-1984371060). The Eventual Consistency issue arises because the rule was created in one region, but the read call for the rule went to another region before the rule data became available in the second region.
Tim updated
`if response != nil && response.StatusCode == 404 { }` code block by adding some retry logic if the rule can not be found after create (404 error), we have to use the code you highlighted to handle other errors.

Please let me know if I miss understood your comment.

**Comment by hkantare** [comment]
@zhenwan I understood we added this logic to support Eventual but we are breaking the scenario which currently exists in master branch https://github.com/IBM-Cloud/terraform-provider-ibm/blob/ddfaf6023adb1a9c55b3d909ac83cbf8dc7a0ee8/ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go#L322

Steps
1) Create a CBR rule via terraform
2) delete CBR using ui/cli/api
3)Rerun terraform plan it shd show diff (resource needs to be reprovisioned)
Can you share the result for above scenario

**Comment by zhenwan** [comment]
@hkantare ok, Now I understand what you meant. I will update the code.
Here is the result by following your steps

```
ibm-context-based-restrictions % terraform plan

ibm_cbr_zone.cbr_zone_instance: Refreshing state... [id=2a5eaec9f4f55b8fc4e76dcb7e9167c6]
data.ibm_cbr_zone.cbr_zone_instance: Reading...
ibm_cbr_rule.cbr_rule_instance: Refreshing state... [id=2a5eaec9f4f55b8fc4e76dcb7e916a3c]
data.ibm_cbr_zone.cbr_zone_instance: Read complete after 0s [id=2a5eaec9f4f55b8fc4e76dcb7e9167c6]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: GetRuleWithContext failed context deadline exceeded
│ {
│     "StatusCode": 404,
│     "Headers": {
│         "Akamai-Grn": [
│             "0.4d155d68.1713802380.4e733676"
│         ],
│         "Cache-Control": [
│             "no-cache,no-store"
│         ],
│         "Connection": [
│             "keep-alive"
│         ],
│         "Content-Length": [
│             "281"
│         ],
│         "Content-Type": [
│             "application/json; charset=utf-8"
│         ],
│         "Date": [
│             "Mon, 22 Apr 2024 16:13:00 GMT"
│         ],
│         "Expires": [
│             "Thursday, 1 January 1970 00:00:00 GMT"
│         ],
│         "Pragma": [
│             "no-cache"
│         ],
│         "Strict-Transport-Security": [
│             "max-age=31536000; includeSubDomains"
│         ],
│         "Transaction-Id": [
│             "1b1fa887-3be7-4576-b582-d7a6c5c3b521"
│         ],
│         "X-Content-Type-Options": [
│             "nosniff"
│         ],
│         "X-Correlation-Id": [
│             "1b1fa887-3be7-4576-b582-d7a6c5c3b521"
│         ],
│         "X-Proxy-Upstream-Service-Time": [
│             "17"
│         ],
│         "X-Ratelimit-Limit": [
│             "10"
│         ],
│         "X-Ratelimit-Remaining": [
│             "9"
│         ],
│         "X-Ratelimit-Reset": [
│             "1713802381"
│         ]
│     },
│     "Result": {
│         "errors": [
│             {
│                 "code": "rule_not_found_in_store",
│                 "message": "The rule '2a5eaec9f4f55b8fc4e76dcb7e916a3c' is not found in store.",
│                 "target": {
│                     "name": "rule_id",
│                     "type": "parameter",
│                     "value": "2a5eaec9f4f55b8fc4e76dcb7e916a3c"
│                 }
│             }
│         ],
│         "status_code": 404,
│         "trace": "1b1fa887-3be7-4576-b582-d7a6c5c3b521"
│     },
│     "RawResult": null
│ }
│ 
│ 
│   with ibm_cbr_rule.cbr_rule_instance,
│   on main.tf line 25, in resource "ibm_cbr_rule" "cbr_rule_instance":
│   25: resource "ibm_cbr_rule" "cbr_rule_instance" {
│ 
╵

```

**Comment by zhenwan** [comment]
@hkantare code has been updated, please re-review.

**Comment by hkantare** [comment]
Thanks 
Can we resolve conflits ibm/acctest/acctest.go

**Review by hkantare — APPROVED** [review]

**Comment by zhenwan** [comment]
@hkantare Resolved the conflicts.
