### PR TITLE
bugfix instance resize

### LINKED ISSUE #2541: On instance resize, check if instance is in running state before stop
### Affected Resource(s)

* ibm_is_instance

### Debug Output

 An action was requested on a resource which is not supported at the current status of the resource.

### Expected Behavior

for instances in already stopped state, provider shouldn't try to stop it again.

### Actual Behavior

Gives an error,  An action was requested on a resource which is not supported at the current status of the resource.
### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by SunithaGudisagarIBM**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #2541 

Output from acceptance testing:

Screenshot 2021-04-26 at 12 02 57 PM

```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISInstance_profile' 

```

### CODE REVIEW

File: ibm/resource_ibm_is_instance.go [hunk 1]
```diff
@@ -1915,21 +1915,35 @@ func instanceUpdate(d *schema.ResourceData, meta interface{}) error {
...
 				return nil
 			}
-			return fmt.Errorf("Error Creating Instance Action: %s\n%s", err, response)
+			return fmt.Errorf("Error Getting Instance (%s): %s\n%s", id, err, response)
 		}
-		_, err = isWaitForInstanceActionStop(instanceC, d.Timeout(schema.TimeoutUpdate), id, d)
-		if err != nil {
-			return err
+
+		if *instance.Status == "running" {
```
Comment (hkantare) [inline ibm/resource_ibm_is_instance.go:1930]: first check instance != nil && *instance.Status
